version: '3.9'
services:
  java_app:
    container_name: java_app
    image: ncarcamo/topeducationmonolitico:latest
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/topedu
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=usach2023
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: usach2023
      POSTGRES_DB: topedu
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql