version: '3.9'
services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - topeducation1
      - topeducation2
  topeducation1:
    container_name: container-topeducation1
    image: ncarcamo/topeducationmonolitico:latest
    build: .
    ports:
      - 8061:8060
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/topedu
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=usach2023
      - DATABASE_PERSISTENTCE=update
    depends_on:
      - java_db
  topeducation2:
    container_name: container-topeducation2
    image: ncarcamo/topeducationmonolitico:latest
    build: .
    ports:
      - 8062:8060
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/topedu
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=usach2023
      - DATABASE_PERSISTENTCE=update
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: usach2023
      POSTGRES_DB: topedu
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql